outputs:
  sustainability:
    indirect_emissions:
      electricity_emissions:
        uom: gCO2-eq/m3
        equation: "electricity_consumption * electricity_emission_factor"
        if: "electricity_consumption > 0"
        precision: 2
        parameters:
          electricity_consumption:
            uom: kWh/m3
            equation: "energy.model_specific_consumption"
          electricity_emission_factor:
            uom: gCO2-eq/kWh
            equation: "db.carbon_intensity_grid"
            precision: 1